INSERT INTO `bancos` (`codigo`, `nome`) VALUES (001,'BANCO DO BRASIL S/A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (002,'BANCO CENTRAL DO BRASIL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (003,'BANCO DA AMAZONIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (004,'BANCO DO NORDESTE DO BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (007,'BANCO NAC DESENV. ECO. SOCIAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (008,'BANCO MERIDIONAL DO BRASIL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (020,'BANCO DO ESTADO DE ALAGOAS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (021,'BANCO DO ESTADO DO ESPIRITO SANTO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (022,'BANCO DE CREDITO REAL DE MINAS GERAIS SA');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (024,'BANCO DO ESTADO DE PERNAMBUCO');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (025,'BANCO ALFA S/A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (026,'BANCO DO ESTADO DO ACRE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (027,'BANCO DO ESTADO DE SANTA CATARINA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (028,'BANCO DO ESTADO DA BAHIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (029,'BANCO DO ESTADO DO RIO DE JANEIRO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (030,'BANCO DO ESTADO DA PARAIBA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (031,'BANCO DO ESTADO DE GOIAS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (032,'BANCO DO ESTADO DO MATO GROSSO S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (033,'BANCO DO ESTADO DE SAO PAULO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (034,'BANCO DO ESADO DO AMAZONAS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (035,'BANCO DO ESTADO DO CEARA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (036,'BANCO DO ESTADO DO MARANHAO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (037,'BANCO DO ESTADO DO PARA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (038,'BANCO DO ESTADO DO PARANA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (039,'BANCO DO ESTADO DO PIAUI S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (041,'BANCO DO ESTADO DO RIO GRANDE DO SUL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (047,'BANCO DO ESTADO DE SERGIPE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (048,'BANCO DO ESTADO DE MINAS GERAIS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (059,'BANCO DO ESTADO DE RONDONIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (070,'BANCO DE BRASILIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (077,'BANCO INTER S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (102,'XP INVESTIMENTOS');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (104,'CAIXA ECONOMICA FEDERAL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (106,'BANCO ITABANCO S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (107,'BANCO BBM S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (109,'BANCO CREDIBANCO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (116,'BANCO B.N.L DO BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (148,'MULTI BANCO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (151,'CAIXA ECONOMICA DO ESTADO DE SAO PAULO');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (153,'CAIXA ECONOMICA DO ESTADO DO R.G.SUL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (165,'BANCO NORCHEM S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (166,'BANCO INTER-ATLANTICO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (168,'BANCO C.C.F. BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (175,'CONTINENTAL BANCO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (184,'BBA - CREDITANSTALT S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (199,'BANCO FINANCIAL PORTUGUES');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (200,'BANCO FRICRISA AXELRUD S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (201,'BANCO AUGUSTA INDUSTRIA E COMERCIAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (204,'BANCO S.R.L S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (205,'BANCO SUL AMERICA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (206,'BANCO MARTINELLI S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (208,'BANCO PACTUAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (210,'DEUTSCH SUDAMERIKANICHE BANK AG');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (211,'BANCO SISTEMA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (212,'BANCO MATONE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (213,'BANCO ARBI S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (214,'BANCO DIBENS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (215,'BANCO AMERICA DO SUL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (216,'BANCO REGIONAL MALCON S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (217,'BANCO AGROINVEST S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (218,'BBS - BANCO BONSUCESSO S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (219,'BANCO DE CREDITO DE SAO PAULO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (220,'BANCO CREFISUL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (221,'BANCO GRAPHUS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (222,'BANCO AGF BRASIL S. A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (223,'BANCO INTERUNION S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (224,'BANCO FIBRA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (225,'BANCO BRASCAN S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (228,'BANCO ICATU S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (229,'BANCO CRUZEIRO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (230,'BANCO BANDEIRANTES S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (231,'BANCO BOAVISTA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (232,'BANCO INTERPART S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (233,'BANCO MAPPIN S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (234,'BANCO LAVRA S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (235,'BANCO LIBERAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (236,'BANCO CAMBIAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (237,'BANCO BRADESCO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (239,'BANCO BANCRED S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (240,'BANCO DE CREDITO REAL DE MINAS GERAIS S.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (241,'BANCO CLASSICO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (242,'BANCO EUROINVEST S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (243,'BANCO STOCK S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (244,'BANCO CIDADE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (245,'BANCO EMPRESARIAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (246,'BANCO ABC ROMA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (247,'BANCO OMEGA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (249,'BANCO INVESTCRED S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (250,'BANCO SCHAHIN CURY S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (251,'BANCO SAO JORGE S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (252,'BANCO FININVEST S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (254,'BANCO PARANA BANCO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (255,'MILBANCO S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (256,'BANCO GULVINVEST S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (258,'BANCO INDUSCRED S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (260,'NUBANK S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (261,'BANCO VARIG S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (262,'BANCO BOREAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (263,'BANCO CACIQUE');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (264,'BANCO PERFORMANCE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (265,'BANCO FATOR S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (266,'BANCO CEDULA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (267,'BANCO BBM-COM.C.IMOB.CFI S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (275,'BANCO REAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (277,'BANCO PLANIBANC S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (282,'BANCO BRASILEIRO COMERCIAL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (291,'BANCO DE CREDITO NACIONAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (294,'BCR - BANCO DE CREDITO REAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (295,'BANCO CREDIPLAN S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (300,'BANCO DE LA NACION ARGENTINA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (302,'BANCO DO PROGRESSO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (303,'BANCO HNF S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (304,'BANCO PONTUAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (308,'BANCO COMERCIAL BANCESA S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (318,'BANCO B.M.G. S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (320,'BANCO INDUSTRIAL E COMERCIAL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (341,'BANCO ITAU S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (346,'BANCO FRANCES E BRASILEIRO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (347,'BANCO SUDAMERIS BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (351,'BANCO BOZANO SIMONSEN S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (353,'BANCO GERAL DO COMERCIO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (356,'ABN AMRO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (366,'BANCO SOGERAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (369,'PONTUAL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (370,'BEAL - BANCO EUROPEU PARA AMERICA LATINA');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (372,'BANCO ITAMARATI S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (375,'BANCO FENICIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (376,'CHASE MANHATTAN BANK S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (388,'BANCO MERCANTIL DE DESCONTOS S/A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (389,'BANCO MERCANTIL DO BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (392,'BANCO MERCANTIL DE SAO PAULO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (394,'BANCO B.M.C. S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (399,'BANCO BAMERINDUS DO BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (409,'UNIBANCO - UNIAO DOS BANCOS BRASILEIROS');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (412,'BANCO NACIONAL DA BAHIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (415,'BANCO NACIONAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (420,'BANCO NACIONAL DO NORTE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (422,'BANCO SAFRA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (424,'BANCO NOROESTE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (434,'BANCO FORTALEZA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (453,'BANCO RURAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (456,'BANCO TOKIO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (464,'BANCO SUMITOMO BRASILEIRO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (466,'BANCO MITSUBISHI BRASILEIRO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (472,'LLOYDS BANK PLC');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (473,'BANCO FINANCIAL PORTUGUES S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (477,'CITIBANK N.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (479,'BANCO DE BOSTON S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (480,'BANCO PORTUGUES DO ATLANTICO-BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (483,'BANCO AGRIMISA S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (487,'DEUTSCHE BANK S.A - BANCO ALEMAO');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (488,'BANCO J. P. MORGAN S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (489,'BANESTO BANCO URUGAUAY S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (492,'INTERNATIONALE NEDERLANDEN BANK N.V.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (493,'BANCO UNION S.A.C.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (494,'BANCO LA REP. ORIENTAL DEL URUGUAY');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (495,'BANCO LA PROVINCIA DE BUENOS AIRES');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (496,'BANCO EXTERIOR DE ESPANA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (498,'CENTRO HISPANO BANCO');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (499,'BANCO IOCHPE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (501,'BANCO BRASILEIRO IRAQUIANO S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (502,'BANCO SANTANDER S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (504,'BANCO MULTIPLIC S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (505,'BANCO GARANTIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (600,'BANCO LUSO BRASILEIRO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (601,'BFC BANCO S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (602,'BANCO PATENTE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (604,'BANCO INDUSTRIAL DO BRASIL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (607,'BANCO SANTOS NEVES S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (608,'BANCO OPEN S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (610,'BANCO V.R. S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (611,'BANCO PAULISTA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (612,'BANCO GUANABARA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (613,'OMNI BANCO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (616,'BANCO INTERPACIFICO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (617,'BANCO INVESTOR S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (618,'BANCO TENDENCIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (621,'BANCO APLICAP S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (622,'BANCO DRACMA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (623,'BANCO PANAMERICANO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (624,'BANCO GENERAL MOTORS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (625,'BANCO ARAUCARIA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (626,'BANCO FICSA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (627,'BANCO DESTAK S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (628,'BANCO CRITERIUM S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (629,'BANCORP BANCO COML. E. DE INVESTMENTO');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (630,'BANCO INTERCAP S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (633,'BANCO REDIMENTO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (634,'BANCO TRIANGULO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (635,'BANCO DO ESTADO DO AMAPA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (637,'BANCO SOFISA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (638,'BANCO PROSPER S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (639,'BIG S.A. - BANCO IRMAOS GUIMARAES');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (640,'BANCO DE CREDITO METROPOLITANO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (641,'BANCO EXCEL ECONOMICO S/A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (643,'BANCO SEGMENTO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (645,'BANCO DO ESTADO DE RORAIMA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (647,'BANCO MARKA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (648,'BANCO ATLANTIS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (649,'BANCO DIMENSAO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (650,'BANCO PEBB S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (652,'BANCO FRANCES E BRASILEIRO SA');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (653,'BANCO INDUSVAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (654,'BANCO A. J. RENNER S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (655,'BANCO VOTORANTIM S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (656,'BANCO MATRIX S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (657,'BANCO TECNICORP S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (658,'BANCO PORTO REAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (702,'BANCO SANTOS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (705,'BANCO INVESTCORP S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (707,'BANCO DAYCOVAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (711,'BANCO VETOR S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (713,'BANCO CINDAM S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (715,'BANCO VEGA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (718,'BANCO OPERADOR S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (719,'BANCO PRIMUS S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (720,'BANCO MAXINVEST S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (721,'BANCO CREDIBEL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (722,'BANCO INTERIOR DE SAO PAULO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (724,'BANCO PORTO SEGURO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (725,'BANCO FINABANCO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (726,'BANCO UNIVERSAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (728,'BANCO FITAL S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (729,'BANCO FONTE S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (730,'BANCO COMERCIAL PARAGUAYO S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (731,'BANCO GNPP S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (732,'BANCO PREMIER S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (733,'BANCO NACOES S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (734,'BANCO GERDAU S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (735,'BANCO NEON');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (736,'BANCO UNITED S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (737,'THECA');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (738,'MARADA');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (739,'BGN');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (740,'BCN BARCLAYS');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (741,'BRP');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (742,'EQUATORIAL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (743,'BANCO EMBLEMA S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (744,'THE FIRST NATIONAL BANK OF BOSTON');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (745,'CITIBAN N.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (746,'MODAL S\A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (747,'RAIBOBANK DO BRASIL');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (748,'SICREDI');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (749,'BRMSANTIL SA');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (750,'BANCO REPUBLIC NATIONAL OF NEW YORK (BRA');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (751,'DRESDNER BANK LATEINAMERIKA-BRASIL S/A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (752,'BANCO BANQUE NATIONALE DE PARIS BRASIL S');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (753,'BANCO COMERCIAL URUGUAI S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (755,'BANCO MERRILL LYNCH S.A');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (756,'BANCO COOPERATIVO DO BRASIL S.A.');
INSERT INTO `bancos` (`codigo`, `nome`) VALUES (757,'BANCO KEB DO BRASIL S.A.');